# Generated by Django 4.2.5 on 2023-10-12 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0003_alter_photoalbum_unique_together'),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbumJourney',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
                ('photo_album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_album.photoalbum')),
            ],
        ),
    ]
