# Generated by Django 4.2.5 on 2023-10-12 01:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_album', '0003_alter_photoalbum_unique_together'),
        ('journey', '0002_photoalbumjourney'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journey',
            unique_together={('title', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='photoalbumjourney',
            unique_together={('journey_id', 'photo_album_id')},
        ),
    ]
