# Generated by Django 4.2.5 on 2023-10-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='used_id',
            new_name='user_id',
        ),
    ]
