# Generated by Django 4.2.5 on 2023-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_used_id_photo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.BinaryField(),
        ),
    ]
