# Generated by Django 4.2.5 on 2023-10-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0003_alter_photoalbum_unique_together'),
        ('photo', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoalbumphoto',
            unique_together={('photo_album_id', 'photo_id')},
        ),
    ]
