# Generated by Django 4.2.5 on 2023-10-08 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photoalbumphoto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbumphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoalbumphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
