# Generated by Django 4.2.5 on 2023-10-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_photo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='photo.tag'),
        ),
    ]
