# Generated by Django 4.2.5 on 2023-11-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_tag_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
