# Generated by Django 4.2.5 on 2023-10-08 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_album', '0002_photoalbum_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoalbum',
            unique_together={('user_id', 'title')},
        ),
    ]
