name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure Flake8 Line Length
      run: echo "[flake8]" > .flake8 && echo "max-line-length = 300" >> .flake8  # Change 100 to desired line length
    - name: Run Flake8 Linter
      run: |
        flake8 .
    - name: Run Tests
      run: |
        python manage.py test apps.user.tests
