name: Security/Penetration Tests

on:
  workflow_run:
    workflows: ["Heroku Deployment"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"

  security-test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
          pip install safety
          pip install requests
          pip install -U urllib3 requests
          pip install  urllib3 chardet

      - name: Run Bandit
        run: bandit -r . -f json -o bandit_results.json || echo "Bandit found issues, but continuing with the workflow"

      - name: Archiving Bandit Results
        uses: actions/upload-artifact@v2
        with:
          name: bandit-results
          path: ./bandit_results.json

    #   - name: Safety Check
    #     run: safety check --full-report --output JSON > safety_report.json

    #   - name: Archiving Safety Results
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: safety-results
    #       path: ./safety_report.json
