name: Maintainability

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install wily

      - name: Build Wily (if needed)
        run: |
          wily build

      - name: Run Wily
        run: |
          # Use the github.event.before and github.sha context variables
          commit_range=${{ github.event.before }}..${{ github.sha }}
          wily report project --revision-range $commit_range > wily-project.txt
          wily report apps --revision-range $commit_range > wily-apps.txt
          wily report apps/photo --revision-range $commit_range > wily-apps-photo.txt
          wily report apps/photo_album --revision-range $commit_range > wily-apps-photo-album.txt
          wily report apps/user --revision-range $commit_range > wily-user.txt
          wily graph apps -m raw.loc,cyclomatic.complexity --revision-range $commit_range

      - name: Archive Wily Reports
        uses: actions/upload-artifact@v2
        with:
          name: wily-reports
          path: |
            ./wily-project.txt
            ./wily-apps.txt
            ./wily-apps-photo.txt
            ./wily-apps-photo-album.txt
            ./wily-user.txt